7unit
jjestyy/JavaSIS-3.20 pull request #5
Opened 2020-04-01 14:59 UTC by jjestyy

ЛР7

2020-04-02 01:58 UTC, Bael requested changes
Анна, вы молодец, проделали большую работу.
Есть несколько замечаний, исправив которые, вы сделаете работу еще лучше :)
1) избавьтесь от Date, сейчас везде используется LocalDate
2) метод формирования запроса со статистикой лучше упростить, блок where сложный. Не бойтесь создавать новые private методы в сервисе, они же никак не повлияют на апи сервиса.
3) при обработке ошибок - важно дать понять что именно случилось
4) используйте автоформатирование IDE, код станет чище без особых усилий.

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/Unit7Application.java
> +	private JdbcTemplate jdbcTemplate;
рекомендуется autowired делать на сеттер, а поле остается как есть. Не критично сейчас.

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/Unit7Application.java
> +    @PostConstruct
форматирование плывет, пользуйтесь автоформатированием студии

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/data/WeatherDataServiceJdbcImpl.java
> +        if(!periodStart.equals("")) {
преобразование даты можно было бы отдать в метод, возвращающий Optional с датой, тогда не было бы трай кэтч под ифом.

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/data/WeatherDataServiceJdbcImpl.java
> +            sql+= String.join(" AND ", conditions);
String.join  хорошо и удобно, вы молодец

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/data/WeatherDataServiceJdbcImpl.java
> +        sql +="GROUP BY MONTH(date), YEAR(date), city "+
проблема с конкатенацией по строкам - не склеить операнды SQL выражения, я бы просто всегда добавлял пробел в начале строки, было бы проще.

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/data/WeatherDataServiceJdbcImpl.java
> +                                formatterOnlyYearAndMonth.parse( rs.getString("year") + "-" + rs.getString("month")));
вытаскивайте преобразование в отдельный метод, не должно быть трай кэтч внутри лямбды, сами видите как выглядит громоздко.

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/model/WeatherRecord.java
> +    private Date date;
этот класс deprecated, он мутабельный и как следствие вызывал кучу проблем.
Рекомендуется использовать java.time.LocalDate, java.time.LocalDateTime

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/shelll/WeatherShellCommands.java
> +            return "Some bad input";
тут непонятно, дело во вводе данных пользователя, или при ошибки при сохранении. Самый простой способ - возвращать стек ошибки, если нет ограничений по интерфейсу. Мы работаем в командной строке, можно предположить что пользователи не будут против полной информации :)

2020-04-02 01:58 UTC, Bael commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/data/WeatherDataServiceJdbcImpl.java
> +        if(conditions.size()>0) {
вам бы формирование блока Where вынести в отдельный метод, передавая туда город и период дат, этот метод используйте безусловно, а он должен вернуть или пустую строку, или полноценную where, которую вы и добавите к своему sql запросу.

2020-04-02 06:55 UTC, jjestyy commented on unit7/src/main/java/com/github/jjestyy/JavaSIS30/unit7/Unit7Application.java
> +    @PostConstruct
а в студии все ровно выглядит, странности

2020-04-03 08:19 UTC, Bael approved these changes
ок, от даты вы избавились, форматирование стало лучше.
Блок where в функцию не вынесли, но пока это не критично, считаю работу выполненной.
Еще забыл упомянуть - никогда не заливайте ключи апи в код, как сделано здесь
  private static Map<String,String> headers = Map.of("x-rapidapi-host", "community-open-weather-map.p.rapidapi.com",
            "x-rapidapi-key","cdd96ad95amsheebcca53e65aac1p136010jsn18e30e4e6350");

Берите их из переменных окружения.

2020-04-08 06:55 UTC, merged